export default async () => {
    return (
        <div className="pt-10 px-8 flex items-center justify-center">
            <div>
                <h1 className="text-6xl">Terms of services</h1>
                <div className="mt-5">
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Non numquam minus adipisci qui repellendus. Velit quo in beatae nostrum natus suscipit ea aut dignissimos vitae et, recusandae reprehenderit, iusto similique delectus dicta mollitia! Quaerat temporibus vel nulla amet deleniti totam rem, inventore omnis molestias, magni commodi dolorem corporis? Id cupiditate quis dolor eos temporibus odio eius praesentium, commodi officia laborum expedita sint debitis veritatis assumenda? Earum nihil reiciendis deleniti delectus adipisci harum distinctio, sint aut! Labore quibusdam non consequuntur sint optio eos, cupiditate quidem ab commodi eveniet sunt autem repellendus molestias suscipit dolor esse temporibus nisi saepe quo, impedit voluptatibus. Alias iste incidunt aliquam suscipit quos. Odio provident neque deserunt, nam nemo reiciendis similique ipsam perspiciatis ab consectetur temporibus vel tempore? Numquam hic consequatur tempore doloremque, libero iure quae veritatis molestias quisquam. Tempore provident, quaerat consequuntur dolorem accusamus nesciunt hic autem illo nemo explicabo quasi. Placeat id ipsum nulla repudiandae iure sequi incidunt iusto, eos fugit? Asperiores illum ut quos saepe quod, voluptates deserunt veritatis ad neque cupiditate est nisi blanditiis sint repellat perferendis rerum! Nostrum id illum, veniam et repellendus tenetur. Laudantium corrupti voluptatibus inventore facilis doloremque facere quia quo laboriosam. Dignissimos, illo doloremque atque doloribus est deserunt nam facilis eum voluptatum, ipsa saepe cumque aliquid repellat in ex. Dolorem voluptate deleniti, beatae recusandae earum quia sit nesciunt pariatur eius dolorum voluptatum adipisci porro, explicabo delectus similique provident commodi quas perspiciatis cum quam! Et maxime vero culpa atque fugiat cumque, repellendus adipisci non sequi aliquid, dicta ipsum architecto iusto corrupti enim quas sed officia accusamus ad qui, tenetur incidunt corporis? Sit ipsam culpa fuga accusamus iusto atque eaque esse temporibus labore a asperiores reprehenderit dolorum laboriosam, omnis dicta odit odio vero. Unde eligendi dolorum non iusto. Perspiciatis ea repudiandae mollitia dolores, repellendus cupiditate eius recusandae quam veritatis facilis? Non.
                </div>
            </div>
        </div>
    )
}